kaj/rsass

src/formalargs.rs
src/functions/mod.rs
src/output_style.rs
src/valueexpression.rs
src/variablescope.rs

Try to use less mutable references to Scopes.  Mainly, there should be no need for a mutable parent from a scope, as I want to be able to let a user-defined function capture the scope it is defined in as a parent, which means multiple scopes must be able to exist with the same parent.
Since `!global` definitions exists in sass, the global scope must still be internally mutable.  I aim to fix this with a `Mutex`.

Refactor scopes

---

src/error.rs
src/lib.rs
src/output_style.rs
src/variablescope.rs
tests/rust_functions.rs

A program using rsass as a library should be able to define functions in rust. An example use-case is that [ructe](https://crates.io/crates/ructe) should be able to define a function to get the uniquified url of a static file.
This means that `Scope`s and the `Value` type needs to be public.

Support user-defined functions in rust

---

check_spec

At least on my machine, `git up` doesn't seem to exist, maybe it's a local alias you're using? These standard commands worked for me at least.

Use standard git commands

---

rls.toml

This is a bug in rls it seems, and the workaround is quite simple, albeit a bit unfortunate.

Add rls.toml so rls doesn’t get confused about bin/lib crates in same project

---

.travis.yml

Choose the easy solution to #11 for now, resulting in less churn.

Pin the rustfmt version to 0.8.4, closes #11

---

check_spec

This fixes a broken pipe in Ruby on Windows when using MSYS2. :)

Manually specify `rg` input will be STDIN for `check_specs stats`

---

check_spec

I've been doing some hacking here, and would really like a `diff` flow to make sure I don't introduce regressions. This is technically possible already, but the current setup commands for `check_spec` (i.e., `cargo` and `git` invocations to build the project and ensure that `sass-spec` is pulled down) print to `stdout` (which they normally should, of course). This PR merely redirects the output of those commands to `stderr` so one can get a more "clean" test failure report for `list_fails`.
```bash
$ git checkout master && ./check_spec > failed_tests_before.txt
$ git checkout my_crazy_experiments && ./check_spec > failed_tests_after.txt
$ diff -u failed_tests_before.txt

Redirect check_spec setup commands to stderr

---

Cargo.toml
src/error.rs
src/functions/macros.rs
src/functions/mod.rs
src/functions/selector.rs
src/output_style.rs
src/parser/formalargs.rs
src/parser/mod.rs
src/parser/selectors.rs
src/parser/strings.rs
src/parser/unit.rs
src/parser/util.rs
src/parser/value.rs
src/variablescope.rs

Lots of wrapping &[u8] in Input (i.e. nom::types::CompleteByteSlice).
Also, the unfortunate return of some String allocations that should not be needed in string parsing.

Update nom to 4.0.

---

src/functions/selector.rs
src/output_style.rs
src/parser/mod.rs
src/parser/selectors.rs
src/sass/item.rs
src/selectors.rs
tests/libsass.rs

Support `@at-root`

---

check_spec
src/error.rs
src/functions/colors_hsl.rs
src/functions/colors_other.rs
src/functions/colors_rgb.rs
src/functions/introspection.rs
src/functions/lists.rs
src/functions/macros.rs
src/functions/maps.rs
src/functions/mod.rs
src/functions/numbers.rs
src/functions/selector.rs
src/functions/strings.rs
src/lib.rs
src/output_style.rs
src/parser/value.rs
src/sass/call_args.rs
src/sass/formal_args.rs
src/sass/string.rs
src/sass/value.rs
src/variablescope.rs
tests/rust_functions.rs

Adds a new error type and changes `Scope#get` to return a `Result`.
`variable-exists` now correctly returns `null` for a defined `null` variable.
Fixes #34

 Raise on accessing an undefined variable

---

Cargo.toml
src/error.rs
src/lib.rs
src/main.rs
src/parser/mod.rs
src/parser/util.rs

As requested in #46.
There are several steps to report errors in a way that is actually helpful to users.

Report file position of parse errors

---

src/parser/formalargs.rs
src/parser/mod.rs
src/parser/selectors.rs
src/parser/strings.rs
src/parser/util.rs
src/parser/value.rs
src/sass/string.rs
src/sass/value.rs
tests/basic/main.rs
tests/css/unknown_directive/mod.rs
tests/parser/interpolate/t11_escaped_literal/mod.rs
tests/parser/interpolate/t12_escaped_double_quoted/mod.rs
tests/parser/interpolate/t13_escaped_single_quoted/mod.rs
tests/parser/interpolate/t14_escapes_literal_numbers/mod.rs
tests/parser/interpolate/t15_escapes_double_quoted_numbers/mod.rs
tests/parser/interpolate/t16_escapes_single_quoted_numbers/mod.rs
tests/parser/interpolate/t17_escapes_literal_lowercase/mod.rs
tests/parser/interpolate/t18_escapes_double_quoted_lowercase/mod.rs
tests/parser/interpolate/t19_escapes_single_quoted_lowercase/mod.rs
tests/parser/interpolate/t20_escapes_literal_uppercase/mod.rs
tests/parser/interpolate/t21_escapes_double_quoted_uppercase/mod.rs
tests/parser/interpolate/t22_escapes_single_quoted_uppercase/mod.rs
tests/parser/interpolate/t23_escapes_literal_specials/mod.rs
tests/parser/interpolate/t24_escapes_double_quoted_specials/mod.rs
tests/parser/interpolate/t25_escapes_single_quoted_specials/mod.rs
tests/parser/interpolate/t44_selector/double_escape/mod.rs
tests/scss/main.rs

Get some more string parsing tests working (some tests starts to fail instead, but they are fewer and higher numbered in the interpolate suite).

Try to impove string parsing/escaping.

---

src/functions/strings.rs
src/output_style.rs
src/parser/strings.rs
src/parser/value.rs
tests/css/main.rs

Handle `url(foo)` as simply a string if possible.  Sometimes, such as `url("foo" + $bar)`, it must be a function returning a string instead.
Partially adresses #42.  Fixes #41.

The url function is special.

---

src/functions/colors_rgb.rs

This PR aims to add support for channel strings, fixing for example test
```
<===> no_alpha/var/arg_1/input.scss
a {b: rgba(var(--foo) 2 3)}
<===> no_alpha/var/arg_1/output.css
a {
b: rgba(var(--foo), 2, 3);
}
<===>
```
These changes decrease the number of failing tests with 18.

Allow channel string in rgba()

---

src/value/number.rs
tests/basic_manual.rs

Resolves https://github.com/kaj/rsass/issues/66
I worked with the following test cases in mind,
```
a {
color: 0.999;
color: -0.999;
color: .999;
color: -.999;
color: 0.999999;
color: -0.999999;
color: 0.9999999999999999;
color: -0.999999999999999;
color: 0;
color: -0;
color: 1;
color: -1;
color: 0.000000000000000001;
}
```
I should note that this PR removes printing of the leading `+`. In addition, I was not completely sure about the leading 0 mechanics -- it seems that libsass prints the leading 0 in all scenarios?
It seems there is also a parsing issue with decimals going back more than 18 places,
```scss
a {
color: 0.0000000000000000001;
}
```
panics with 
```
thread 'main' panicked at 'attempt to multiply with overflow', src\parser\value.rs:302:62
note: run with `RUST_BACKTRACE=1` …
```

Refactor printing of numbers

---

src/value/number.rs
tests/basic_manual.rs
tests/spec/non_conformant/misc/mod.rs

This builds on https://github.com/kaj/rsass/pull/67. It's a pretty minor change but removing the allocation to add to the last char is exciting. It also changes how the negative sign is emitted such that `-0.0000000000000000001` is not printed as `-0`. 
Performance gains are small but noticeable. For a 10,000 line file that looks like
```
a {
color: 0.45684318453159234;
color: 0.32462456760120406;
color: 0.8137736535327419;
color: 0.7358225117215007;
color: 0.17214528398099915;
color: 0.49902566583569585;
color: 0.338644100262644;
color: 0.20366595024608847;
color: 0.9913235248842889;
color: 0.4504985674365235;
color: 0.4019760103825616;
color: 0.050337450640631;
color: 0.5651205053784689;
color: 0.3858205416141207;
color: 0.09217890891037928;
...
```
I was able to see a consistent …

Further optimize number printing

---

src/parser/strings.rs
tests/fuzz_cases.rs

I found through fuzzing that the minimized input `\d00000` panics upon unwrapping None. This PR adds that input as a test, and refactors escaped_char() to use additional combinators instead of unwrap calls.

Remove three unwraps from escaped_char

---

src/functions/colors_hsl.rs
src/functions/colors_rgb.rs
tests/spec/core_functions/color/hsl/four_args/mod.rs
tests/spec/core_functions/color/hsl/one_arg/mod.rs
tests/spec/core_functions/color/hsla/four_args/mod.rs
tests/spec/core_functions/color/hsla/one_arg/mod.rs
tests/spec/core_functions/color/rgb/one_arg/mod.rs
tests/spec/core_functions/color/rgba/one_arg/mod.rs
tests/spec/core_functions/meta/mod.rs

Support `rgba(r g b / a)` and `hsla(h s l / a)` functions, i.e. the `channels` parameter with div-separated alpha channel.

More strange ways to call rgb/rgba function.

---

src/error.rs
src/functions/selector.rs
src/lib.rs
src/parser/error.rs
src/parser/mod.rs
src/parser/pos.rs
src/selectors.rs
src/spectest/main.rs
src/spectest/testfixture.rs
src/variablescope.rs
tests/spec/libsass_closed_issues/mod.rs
tests/spec/main.rs
tests/spec/non_conformant/scss_tests/mod.rs

Unify `ParseError` and `Error`, so the ParseError case of Error just contains a ParseError struct. This also makes the reporting of a parse error look like in dart-sass, including a copy of the actual text on the line where it occurred.
Add a `check` method in `ParseError` to convert a `nom::IResult` to a `Result` with a possible `ParseError`, and get rid of the bogus conversion from `nom::IResult` to `Error::S`.

Do some refactoring of parse error handling

---

Cargo.toml
src/functions/mod.rs
src/functions/selector.rs
src/lib.rs
src/output/style.rs
src/parser/error.rs
src/parser/formalargs.rs
src/parser/mod.rs
src/parser/pos.rs
src/parser/selectors.rs
src/parser/strings.rs
src/parser/unit.rs
src/parser/util.rs
src/parser/value.rs
src/sass/item.rs
src/selectors.rs
src/spectest/main.rs
src/spectest/testfixture.rs
src/variablescope.rs
tests/spec/main.rs

Use [`nom-locate`] to provide location of errors, improving error reporting.
[`nom-locate`]: https://crates.io/crates/nom-locate

Improve how positions in input is managed.

---

CHANGELOG.md
src/css/call_args.rs
src/css/value.rs
src/css/valueformat.rs
src/functions/color/hsl.rs
src/functions/color/other.rs
src/functions/color/rgb.rs
src/functions/math.rs
src/functions/mod.rs
src/functions/string.rs
src/parser/value.rs
src/sass/call_args.rs
src/sass/formal_args.rs
src/sass/item.rs
src/sass/string.rs
src/sass/value.rs
src/selectors.rs
src/value/mod.rs
src/value/number.rs
src/value/operator.rs
src/variablescope.rs
tests/basic_manual.rs
tests/rust_functions.rs
tests/spec/core_functions/math/atan2/mod.rs
tests/spec/core_functions/math/mod.rs
tests/spec/core_functions/math/pow/mod.rs
tests/spec/non_conformant/basic/mod.rs
tests/spec/values/maps/mod.rs

- Encapuslate the difference between a `Ratio<isize>` and a `Ratio<BigInt>` inside the `Number` type, so their use outside of `number.rs` is identical.
- Add a third case, the `Number` may be a `f64`.  This allows <del>semi-</del>correct handling of Infinity, -Infinity and NaN.
- For value comparisons, we <del>consider NaN == NaN, Infinity == Infinity and -Infinity == -Infinity.  This differs from sane and normal float handling in Rust, where each NaN or infinity is unique.  Therefore, `f64` is encapsulated in a type that implements `Ord` and `Eq` (and not just their partials)</del> <ins>actually treat float value with normal PartialOrd behaviour</ins>.
- `css::Value`, `sass::Value` and lots of related types no longer implement `Ord`.  `PartialOrd` is enough.
- Power and trigonometric …

Refactor and improve numbers

---

CHANGELOG.md
src/output/style.rs
src/parser/mod.rs
src/sass/item.rs
src/sass/mod.rs
src/sass/string.rs
src/variablescope.rs
tests/spec/core_functions/meta/load_css/mod.rs
tests/spec/core_functions/meta/mod.rs
tests/spec/core_functions/modules/mod.rs

Also, loading a module that cannot be loaded is an error (a nonexistent (new?) standard module, an extension for another implementation, or any user-provided module, since those are not yet supported).

Handle `@use module as *`.

---

src/error.rs
src/file_context.rs
src/lib.rs
src/main.rs
src/output/style.rs
src/parser/mod.rs
src/spectest/main.rs
src/spectest/testfixture.rs
tests/basic_manual.rs
tests/rust_functions.rs
tests/spec/main.rs

This change allows customizing how files are loaded.
Changes:
* Add a new trait `Context`, implemented by `FileContext`.
* Change the public signature of the method `Format.write_root()` (and related private ones) to accepting this trait instead of a `FileContext` directly.
* Add a new function `parse_scss_readable()`, like `do_parse_scss_file()` but accepting a `Read`.
I was considering renaming the original functions from `X_file()` to `X_path()` since they accepts paths instead of files. Then the new ones that accept `Read` can become `X_file()`.
This would be a breaking change, however.
* Add a function `parse_imported_scss_readable()`, like `parse_imported_scss_file()`
This function isn't used or public so it causes a warning, it can probably be removed.
* Change a field of …

Allow customizing file loading using the new Context trait

---

src/functions/color/hsl.rs
src/functions/color/hwb.rs
src/functions/color/mod.rs
src/functions/color/other.rs
src/functions/color/rgb.rs
src/functions/list.rs
src/functions/macros.rs
src/functions/map.rs
src/functions/math.rs
src/functions/meta.rs
src/functions/mod.rs
src/functions/module.rs
src/functions/selector.rs
src/functions/string.rs
src/output/style.rs
src/parser/formalargs.rs
src/parser/mod.rs
src/parser/value.rs
src/sass/formal_args.rs
src/sass/item.rs
src/sass/mod.rs
src/sass/name.rs
src/sass/value.rs
src/variablescope.rs
tests/rust_functions.rs
tests/spec/core_functions/math/mod.rs

So write a struct Module istead of using a raw BTreeMap.
Also introduce a Name to to use as a key in both Module and Scope, and lots of refactoring of scope.

A module can contain variables.

---

CHANGELOG.md
src/css/value.rs
src/functions/color/hsl.rs
src/functions/color/hwb.rs
src/functions/color/other.rs
src/functions/color/rgb.rs
src/functions/mod.rs
src/lib.rs
src/sass/value.rs
src/value/colors/convert.rs
src/value/colors/hsla.rs
src/value/colors/hwba.rs
src/value/colors/mod.rs
src/value/colors/rgba.rs
src/value/mod.rs
src/value/operator.rs
tests/rust_functions.rs
tests/spec/core_functions/color/mod.rs
tests/spec/libsass/color_functions/mod.rs

Provide distinct types for Rgba and Hsla colors.  Provide translations between them and a Color enum that can be either.  This way, a Hsla color can remember its hue even if it gets zero saturation.

Color is either Rgba or Hsla.

---

CHANGELOG.md
src/functions/color/hsl.rs
src/functions/color/hwb.rs
src/functions/color/mod.rs
src/functions/color/other.rs
src/functions/color/rgb.rs
src/functions/mod.rs
src/value/colors/convert.rs
src/value/colors/hsla.rs
src/value/colors/hwba.rs
src/value/colors/mod.rs
src/value/colors/rgba.rs

Refactor color handling, mainly by making the fields of the different color structs private, so invariants can be upheld.

Color integrity

---

CHANGELOG.md
src/css/call_args.rs
src/css/mod.rs
src/css/value.rs
src/error.rs
src/lib.rs
src/sass/mod.rs
src/sass/value.rs
src/value/mod.rs
tests/rust_functions.rs

Expose the `value` module rather than the individual types it defines.  Also, `sass::Item` is public, so there is no need to reexport it as `Item`.
Also, add documentation to a lot of things that lacked it.

Fewer types in crate root

---

CHANGELOG.md
src/css/value.rs
src/css/valueformat.rs
src/functions/color/hsl.rs
src/functions/color/hwb.rs
src/functions/color/other.rs
src/functions/color/rgb.rs
src/functions/list.rs
src/functions/math.rs
src/functions/string.rs
src/parser/mod.rs
src/parser/value.rs
src/sass/value.rs
src/value/mod.rs
src/value/number.rs
src/value/numeric.rs
src/value/operator.rs
src/value/range.rs
tests/rust_functions.rs

Provide a type `value::Numeric` which combines a `Number` with a `Unit`, and use that type in `sass::Value` and `css::Value`.

A `Numeric` is a Number with a Unit

---

CHANGELOG.md
src/parser/value.rs
src/sass/functions/color/hsl.rs
src/sass/functions/color/other.rs
src/sass/functions/color/rgb.rs
src/sass/functions/math.rs
src/value/mod.rs
src/value/number.rs
src/value/numeric.rs
src/value/operator.rs
src/value/range.rs
src/value/unit.rs
src/value/unitset.rs
tests/rust_functions.rs
tests/spec/core_functions/math/mod.rs
tests/spec/core_functions/meta/mod.rs
tests/spec/libsass/mod.rs
tests/spec/libsass/units/conversion/mod.rs
tests/spec/libsass_closed_issues/mod.rs

This makes e.g. `abs(-7px / 4em) * 1em` evaluate correctly, to `1.75px`.
Also correct the `dpi`/`dpcm`/`dppx` conversion factors, which were bogus.

Implement values with multiple units.

---

CHANGELOG.md
src/parser/value.rs
src/value/number.rs

No need to parse the first as isize-based limited numbers and then try again as bignum number when we can parse directly into Number which will handle any overflow.

Parse numbers directly as Number.

---

CHANGELOG.md
src/css/call_args.rs
src/css/value.rs
src/css/valueformat.rs
src/parser/mod.rs
src/parser/value.rs
src/sass/formal_args.rs
src/sass/functions/color/rgb.rs
src/sass/functions/list.rs
src/sass/functions/map.rs
src/sass/value.rs
src/selectors.rs
src/value/operator.rs
tests/spec/core_functions/list/join/empty.rs
tests/spec/core_functions/list/join/single.rs
tests/spec/core_functions/list/utils.rs

A list can have "undecided" separator, which affects how it will combine with other lists.

Support undecided sepators.

---

CHANGELOG.md
src/parser/mod.rs
src/parser/selectors.rs
src/sass/functions/selector.rs
src/selectors.rs
tests/spec/core_functions/selector/append.rs
tests/spec/core_functions/selector/nest.rs
tests/spec/core_functions/selector/parse/selector.rs
tests/spec/libsass_closed_issues/issue_1583.rs
tests/spec/libsass_closed_issues/issue_1741.rs

Improve how arguments are recieved and resulting selectors are converted to values.
Also improve how backrefs are handled in PseudoElement and Pseudo selectors.

Improve selector functions

---

CHANGELOG.md
src/output/transform.rs
src/parser/mod.rs
src/sass/item.rs
tests/spec/directives/test_use/error/with.rs
tests/spec/directives/test_use/with.rs

Support `@use ... with ($name: value, ...)`.

Modules can now be configured

---

src/output/cssbuf.rs
src/output/format.rs
src/output/transform.rs
src/parser/imports.rs
src/parser/mod.rs
src/sass/item.rs
src/sass/mod.rs
src/spectest/testrunner.rs
src/variablescope.rs
tests/spec/core_functions/meta/function_exists.rs
tests/spec/core_functions/meta/get_function/different_module.rs
tests/spec/core_functions/meta/global_variable_exists.rs
tests/spec/core_functions/meta/keywords.rs
tests/spec/core_functions/meta/mixin_exists.rs
tests/spec/core_functions/meta/module_functions.rs
tests/spec/core_functions/meta/module_variables.rs
tests/spec/core_functions/meta/variable_exists.rs
tests/spec/core_functions/modules/general.rs
tests/spec/directives/import/configuration.rs
tests/spec/directives/test_use/css/order.rs
tests/spec/directives/test_use/with.rs
tests/spec/testrunner.rs

Support most of `@forward` and `@use` with modules.  This includes support for `as`, `show`, and `hide`, and some support for `with`, though configuration can only be applied to the directly loaded module yet, not to modules used by it or forwarded into it.

Support `@forward`, improve `@use`.

---

CHANGELOG.md
src/css/call_args.rs
src/css/mod.rs
src/css/string.rs
src/css/value.rs
src/css/valueformat.rs
src/output/cssbuf.rs
src/output/transform.rs
src/sass/functions/color/mod.rs
src/sass/functions/color/other.rs
src/sass/functions/list.rs
src/sass/functions/math.rs
src/sass/functions/meta.rs
src/sass/functions/mod.rs
src/sass/functions/selector.rs
src/sass/functions/string.rs
src/sass/string.rs
src/sass/value.rs
src/selectors.rs
src/value/operator.rs
src/variablescope.rs
tests/basic_manual.rs

A `css::Value::Literal` now contains a `CssString` rather than a `String` and a `Quotes`.  Evaluating a `SassString` also returns a `CssString`.

struct CssString

---

Cargo.toml
src/sass/functions/math.rs

This has the advantage of removing a total of about 8 dependencies and adds support for wasm browser environments.

Replace `rand` with `fastrand`

---

.github/workflows/rust.yml
CHANGELOG.md
src/spectest/main.rs
src/spectest/options.rs
src/spectest/testfixture.rs
src/spectest/testrunner.rs

See if clippy works as a github action.

Enable clippy in CI.

---

CHANGELOG.md
src/file_context.rs
src/lib.rs
src/main.rs
src/output/transform.rs
src/parser/mod.rs
src/parser/pos.rs
src/spectest/testrunner.rs
tests/spec/testrunner.rs

* The functions `parse_scss_file` and `parse_scss_path` is removed. Use `SourceFile` (maybe from a `FileContext`) instead.
* Some API changes (mayinly using `SourceFile` as return type) in `FileContext` and `FsF ileContext`.
* Refactor source file handling.  Instead of creating new FileContexts wrapping the original for each file for searching for local paths in that file, use the SourceName of the containing file to find local paths.

Refactor file handling.

---

CHANGELOG.md
src/css/mod.rs
src/css/string.rs
src/css/util.rs
src/css/value.rs
src/css/valueformat.rs
src/parser/css_function.rs
src/parser/mod.rs
src/parser/value.rs
src/sass/call_args.rs
src/sass/functions/math.rs
src/sass/functions/meta.rs
src/sass/functions/mod.rs
src/sass/value.rs
src/value/number.rs
src/value/operator.rs
tests/basic_manual.rs
tests/spec/core_functions/meta/type_of.rs
tests/spec/values/calculation/calc/no_operator.rs
tests/spec/values/calculation/calc/operator.rs
tests/spec/values/calculation/calc/simplify.rs
tests/spec/values/calculation/clamp.rs
tests/spec/values/calculation/max.rs
tests/spec/values/calculation/min.rs

Calc is a very special function, since the sass implementation extrends but does not replace the css function.  So depending on the arguments, it may be either.

Improve the `calc` function.

---

CHANGELOG.md
src/parser/pos.rs
src/parser/unit.rs
src/sass/functions/mod.rs
src/sass/value.rs
src/value/unit.rs
src/value/unitset.rs
tests/spec/values/calculation/calc/error/complex_units.rs
tests/spec/values/calculation/calc/error/known_incompatible/angle.rs
tests/spec/values/calculation/calc/error/known_incompatible/complex.rs
tests/spec/values/calculation/calc/error/known_incompatible/frequency.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/ch.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/cm.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/em.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/ex.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/mm.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/pc.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/pt.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/px.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/q.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/rem.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/test_in.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/vh.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/vmax.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/vmin.rs
tests/spec/values/calculation/calc/error/known_incompatible/length/vw.rs
tests/spec/values/calculation/calc/error/known_incompatible/minus.rs
tests/spec/values/calculation/calc/error/known_incompatible/time.rs
tests/spec/values/calculation/calc/error/value.rs

When the `calc` function evaluates partially (to a `calc(...)` call),
that call should be a valid css calc call.

Add some checks for `calc`.

---

CHANGELOG.md
src/file_context.rs
tests/basic/defs/_foo.scss
tests/basic/defs/_index.scss

Work some more with paths as `Path` and use `join` for joining a local
name with the base paths.  The local parts are still strings that may
contain `/` as separator, but base is properly used as OS-native
paths.
May fix #143 ?

Attempt more path improvements

---

CHANGELOG.md
src/css/call_args.rs
src/css/mod.rs
src/css/util.rs
src/css/value.rs
src/error.rs
src/parser/css/values.rs
src/parser/formalargs.rs
src/parser/pos.rs
src/parser/strings.rs
src/parser/value.rs
src/sass/call_args.rs
src/sass/functions/meta.rs
src/sass/functions/mod.rs
src/sass/functions/string.rs
src/sass/value.rs
tests/spec/css/functions/var.rs
tests/spec/css/plain/import/conditions.rs
tests/spec/libsass_closed_issues/issue_2140.rs

It is a function, remove it from the special_function_misc
fallback handling.

No longer handle `var` as a string.

---

CHANGELOG.md
src/output/transform.rs
src/parser/mod.rs
src/sass/formal_args.rs
src/sass/functions/math.rs
src/sass/item.rs
src/sass/mixin.rs
src/variablescope.rs
tests/rust_functions.rs
tests/spec/core_functions/math/variables.rs
tests/spec/core_functions/meta/load_css/error.rs
tests/spec/core_functions/meta/load_css/twice.rs
tests/spec/directives/forward/error/with.rs
tests/spec/directives/forward/member/bare.rs
tests/spec/directives/forward/member/import/forward_to_import.rs
tests/spec/directives/forward/member/import/import_to_forward/use_to.rs
tests/spec/directives/forward/member/shadowed.rs
tests/spec/directives/forward/member/test_as.rs
tests/spec/directives/forward/member/visibility.rs
tests/spec/directives/test_use/error/member.rs
tests/spec/directives/test_use/error/with.rs
tests/spec/directives/test_use/member/namespaced.rs
tests/spec/directives/test_use/member/use_to_import.rs

This means setting a variable may now fail.

Make it possible to set a variable in a module.

---

CHANGELOG.md
src/error.rs
src/main.rs
src/output/transform.rs
src/sass/formal_args.rs
src/sass/functions/color/mod.rs
src/sass/functions/meta.rs
src/sass/mixin.rs
src/sass/value.rs
tests/spec/main.rs

Make `Debug` formatting of `rsass::Error` look like the `Display`
output, but without the "Error: " prefix.  This makes the error
display correctly if returned from a `main` function.
This also puts the "Error: " prefix in one single place, rather than
repeating it in error messages all over the codebase.

Improve error formatting code.

---

CHANGELOG.md
src/input/context.rs
src/lib.rs
src/main.rs
src/output/format.rs
src/output/mod.rs
src/output/transform.rs
src/spectest/testrunner.rs
tests/rust_functions.rs
tests/spec/testrunner.rs

This makes `Context`, it's configuration methods and the `transform` method the main interface into rsass.

Make the global scope of a context acessible.

---

src/css/call_args.rs
src/css/selectors.rs
src/error.rs
src/lib.rs
src/output/transform.rs
src/sass/call_args.rs
src/sass/callable.rs
src/sass/formal_args.rs
src/sass/functions/call_error.rs
src/sass/functions/color/channels.rs
src/sass/functions/color/hsl.rs
src/sass/functions/color/hwb.rs
src/sass/functions/color/mod.rs
src/sass/functions/color/other.rs
src/sass/functions/color/rgb.rs
src/sass/functions/list.rs
src/sass/functions/map.rs
src/sass/functions/math.rs
src/sass/functions/meta.rs
src/sass/functions/mod.rs
src/sass/functions/selector.rs
src/sass/functions/string.rs
src/sass/mixin.rs
src/sass/mod.rs
src/sass/value.rs
src/variablescope.rs
tests/rust_functions.rs

Inside a function implementation, errors ends up as `CallError`. This can be combined with a call position to yield a `crate::Error`.

Refactor errors some more.

---

CHANGELOG.md
src/css/atrule.rs
src/css/item.rs
src/css/rule.rs
src/css/value.rs
src/error.rs
src/input/context.rs
src/output/cssbuf.rs
src/output/cssdata.rs
src/output/cssdest.rs
src/output/mod.rs
src/output/transform.rs
src/parser/css/mod.rs
src/variablescope.rs
tests/basic_manual.rs
tests/spec/directives/import/nested.rs
tests/spec/libsass/mixins_and_media_queries.rs

Instead of just writing output to a file (or buffer), build the complete result css as a data tree.  This is a requirement for implementing `@extend`, and it cleans up some of the ouptput/transform code.  Also some actual improvement in at-rule / rule interaction.

Refactor css output.

---

.github/workflows/rust.yml
rsass-cli/Cargo.toml
rsass/Cargo.toml

So require rust 1.64 for rsass-cli, while trying to keep compat back to 1.58.1 for rsass the library crate.
This raises MSRV for the library itself from 1.56.1 to 1.58.1, allowing direct variable capture in format strings and some other rust features.
Also, less verbose build logs.

Clap now requires rust 1.64.

---

CHANGELOG.md
rsass/src/parser/mod.rs
rsass/src/parser/strings.rs
rsass/src/sass/string.rs
rsass/tests/basic_manual.rs

The values of custom properties (css variables) are not parsed as ordinary values, but as a kind of extended strings.  Up to now, it was either a quoted string or a unquoted specially extended string.  Now, it is instead the extended string directly, but the extended string can contain quoted strings.
Fixes #175.

Be more flexible in custom values.

---

CHANGELOG.md
rsass/src/css/binop.rs
rsass/src/parser/strings.rs
rsass/src/sass/functions/mod.rs
rsass/src/sass/string.rs
rsass/src/value/operator.rs
rsass/tests/spec/values/calculation/calc/constant.rs
rsass/tests/spec/values/calculation/calc/error/syntax.rs

The `calc(...)` function can be parsed as a special string if, but only if, it contains a string interpolation.  In other cases, it is now parsed as a proper function call.  This change improves how it is evaluated.

Improve `calc(...)` support.

---

CHANGELOG.md
rsass/src/css/mod.rs
rsass/src/css/selectors.rs
rsass/src/output/transform.rs
rsass/src/sass/functions/selector.rs
rsass/src/sass/value.rs
rsass/src/variablescope.rs

Move the separate backref selector from `Selector` to a new struct `SelectorCtx`, to have it only where needed.  This simplifies selector handling in rules and functions.

Refactor selector handling.

---

CHANGELOG.md
rsass/src/css/rule.rs
rsass/src/css/selectors.rs
rsass/src/parser/selectors.rs
rsass/src/parser/strings.rs
rsass/tests/basic_manual.rs
rsass/tests/spec/css/selector/placeholder.rs
rsass/tests/spec/libsass_closed_issues/issue_167.rs
rsass/tests/spec/libsass_closed_issues/issue_1996.rs
rsass/tests/spec/libsass_closed_issues/issue_239.rs
rsass/tests/spec/parser/selector.rs

They are still parsed of the internal data representation, so they can be used when implementing `@extend`.
This is a part of the larger work to support `@extend`, #65.

Filter out placeholder selectors.

---

CHANGELOG.md
rsass/src/css/mod.rs
rsass/src/css/selectors.rs
rsass/src/css/selectors/cssselectorset.rs
rsass/src/css/selectors/logical.rs
rsass/src/css/selectors/pseudo.rs
rsass/src/parser/error.rs
rsass/src/sass/functions/mod.rs
rsass/src/sass/functions/resolvedargs.rs
rsass/src/sass/functions/selector.rs
rsass/tests/spec/core_functions/selector/nest/error.rs
rsass/tests/spec/core_functions/selector/nest/list.rs

This adds supports for sass backref (`&`) is `LogicalSelectorSet` and introduces a new type, `CssSelectorSet`, which is guaranteed to not contain backrefs.
Functions that are intended to not accept backrefs are moved to `CssSelectorSet`.  The `nest` function is also created as a `CssSelectorSet` method, as the first argument may not contain backrefs.  The other argument is a `LogicalSelectorSet`, though.

Use logical selectors in nest.

---

CHANGELOG.md
rsass/src/css/selectors/attribute.rs
rsass/src/css/selectors/cssselectorset.rs
rsass/src/css/selectors/logical.rs
rsass/src/css/selectors/pseudo.rs
rsass/src/css/selectors/selectorset.rs
rsass/src/parser/css/mod.rs
rsass/src/parser/css/strings.rs
rsass/src/parser/mod.rs
rsass/src/parser/util.rs
rsass/src/sass/functions/selector.rs
rsass/tests/spec/core_functions/selector/is_superselector/simple/pseudo/arg.rs
rsass/tests/spec/core_functions/selector/is_superselector/simple/pseudo/selector_arg/nth_child.rs
rsass/tests/spec/core_functions/selector/is_superselector/simple/pseudo/selector_arg/nth_last_child.rs
rsass/tests/spec/core_functions/selector/is_superselector/simple/pseudo/selector_arg/slotted.rs
rsass/tests/spec/core_functions/selector/nest/error.rs
rsass/tests/spec/core_functions/selector/parse/error.rs
rsass/tests/spec/core_functions/selector/parse/selector.rs
rsass/tests/spec/core_functions/selector/unify/simple/pseudo.rs

Parse next-generation css selectors directly (rather than parsing as the old type and converting to the new).  Fixes the `selector.parse` function and improves support for other selector functions.

Parse new selectors

---

CHANGELOG.md
rsass/src/sass/functions/color/hsl.rs
rsass/src/sass/functions/color/hwb.rs
rsass/src/sass/functions/color/mod.rs
rsass/src/sass/functions/color/other.rs
rsass/src/sass/functions/color/rgb.rs
rsass/src/value/colors/convert.rs
rsass/src/value/colors/hsla.rs
rsass/src/value/colors/hwba.rs
rsass/src/value/colors/mod.rs
rsass/src/value/colors/rgba.rs
rsass/tests/spec/core_functions/color/adjust/hwb.rs
rsass/tests/spec/core_functions/color/hsl/four_args/out_of_gamut.rs
rsass/tests/spec/core_functions/color/hwb/four_args.rs
rsass/tests/spec/core_functions/color/hwb/one_arg.rs
rsass/tests/spec/core_functions/color/rgb/four_args/clamped.rs

A color channel can now be NaN or infinite, so represent them as f64 rather than as rationals.  This also makes the color structs smaller, as the rational numbers were 16 bytes each while a f64 is 8.

Make all color channels f64.

---

CHANGELOG.md
rsass/src/css/selectors/selector.rs
rsass/tests/spec/core_functions/selector/unify/complex/combinators/child.rs
rsass/tests/spec/core_functions/selector/unify/complex/combinators/multiple.rs
rsass/tests/spec/core_functions/selector/unify/complex/combinators/next_sibling.rs
rsass/tests/spec/core_functions/selector/unify/complex/combinators/sibling.rs
rsass/tests/spec/core_functions/selector/unify/complex/rootish.rs
rsass/tests/spec/core_functions/selector/unify/compound.rs
rsass/tests/spec/main.rs
rsass/tests/spec/non_conformant/extend_tests/t127_test_nested_extender_with_early_child_selector.rs
rsass/tests/spec/non_conformant/extend_tests/t142_test_combinator_unification_double_tilde.rs
rsass/tests/spec/non_conformant/extend_tests/t146_test_combinator_unification_tilde_plus.rs
rsass/tests/spec/non_conformant/extend_tests/t150_test_combinator_unification_tilde_plus.rs
rsass/tests/spec/non_conformant/extend_tests/t156_test_combinator_unification_double_angle.rs
rsass/tests/spec/non_conformant/extend_tests/t158_test_combinator_unification_double_angle.rs
rsass/tests/spec/non_conformant/extend_tests/t160_test_combinator_unification_double_plus.rs
rsass/tests/spec/non_conformant/extend_tests/t162_test_combinator_unification_double_plus.rs
rsass/tests/spec/non_conformant/extend_tests/t176_test_combinator_unification_nested.rs
rsass/tests/spec/non_conformant/extend_tests/t177_test_combinator_unification_nested.rs
rsass/tests/spec/non_conformant/extend_tests/t178_test_combinator_unification_with_newlines.rs
rsass/tests/spec/non_conformant/extend_tests/t238_unify_root_pseudoelement.rs

Some order of unified selectors was cleaned up in dart sass, and can now be cleaned up in rsass.

Update tests to 2024-09-30
